FROM rust:latest

# Install cargo-watch to automatically restart the server when code changes
RUN cargo install cargo-watch

WORKDIR /app

# When the container starts, watch for changes and restart cargo run automatically
CMD ["cargo", "watch", "-x", "run"]
